learner:
  type_: EWC
  lambda_: 1.0

hpsearch:
  args:
    "learner.lambda_":
      type_: float
      low: 1
      high: 10000
      log: true
    "learner.gamma":
      type_: float
      low: 0.9
      high: 1.0
