learner:
  type_: LWF

hpsearch:
  args:
    # Weight of the distillation loss term. 
    "learner.alpha":
      type_: float
      low: 0.0
      high: 2.0

    # Distillation temperature.
    "learner.temperature":
      type_: float
      low: 1.0
      high: 10.0
      log: true

