[project]
name = "blurry-ocl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "capymoa",
    "cattrs>=26.1.0",
    "click>=8.3.2",
    "doit>=0.37.0",
    "loguru>=0.7.3",
    "mashumaro>=3.20",
    "omegaconf>=2.3.0",
    "optuna-dashboard>=0.20.0",
    "optuna>=4.8.0",
    "psycopg[binary]>=3.3.4",
    "tensorboard>=2.20.0",
]

[tool.uv.sources]
capymoa = { path = "../CapyMOA", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["."]
