bases:
- scenario.yml
- boundary/01_gradual.yml
- learner/EWC.yml
- drift_detector/ADWIN.yml
drift_detector:
  delta: 0.09666826413877098
learner:
  buffer_capacity: 256
  fim_batch_size: 32
  gamma: 1.0
  lambda_: 896.8380915103317
  lr: 0.0038674075933941617
