drift_detector:
  type_: DDM
  error_stream_type: ERROR

hpsearch:
  args:
    "drift_detector.min_n_instances":
      type_: int
      low: 10
      high: 1000
      log: true
    "drift_detector.out_control_level":
      type_: float
      low: 1.5
      high: 4.0
      step: 0.25
