drift_detector:
  type_: PH
  error_stream_type: ERROR
  min_n_instances: 100


hpsearch:
  args:
    "drift_detector.delta":
      type_: float
      low: 0.0001
      high: 0.01
      log: true
    "drift_detector.lambda_":
      type_: int
      low: 1
      high: 50
      log: true
    "drift_detector.alpha":
      type_: float
      low: 0.9
      high: 0.9999