scenario:
  name: DomainCIFAR100

model:
  type_: resnet20_32x32

mb_train: 32
mb_test: 128

hpsearch:
  n_trials: 30
  args:
    "learner.lr":
      type_: float
      low: 0.0001
      high: 0.01
      log: true