label: debug
device: cuda
mb_train: 32
mb_test: 128
disable_progress_bar: true
seed: 5
trial: 0

scenario:
  name: RotatedTinyMNIST
  normalize_features: true
  gradual: 0.0
  label: abrupt
  validation: false
drift_detector:
  max_delay: 500
  rate_period: 1000
  max_early_detection: 0
  reset_on_drift: true
  error_stream_type: CE
  label: BEST
  delta: 0.24742982318199566
  type_: ADWIN
learner:
  lr: 0.001
  type_: LWF
model:
  type_: MLP

