bases:
  - drift_detector/ADWIN.yml
  - learner/FT.yml
  - model/Perceptron.yml
  - scenario/rfmnist.yml

mb_train: 16

hpsearch:
  n_trials: 5
  args:
    "learner.lr":
      type_: float
      low: 1e-5
      high: 1e-1
      log: true
