hpsearch:
  n_trials: 1
  metric: accuracy_seen_avg
  maximize: true
  mode: w # Overwrite study if it already exists
  n_jobs: 4

  args:
    "optimizer.lr":
      type_: float
      low: 1e-5
      high: 1e-1
      log: true
