bases:
- scenario.yml
- boundary/00_abrupt.yml
- learner/EWC.yml
- drift_detector/ADWIN.yml
drift_detector:
  delta: 0.07892971245991784
learner:
  buffer_capacity: 256
  fim_batch_size: 32
  gamma: 1.0
  lambda_: 967.3775395602892
  lr: 0.005853975683963141
